# ORLIB
DATASET_FILE = '130/cap134'
ORLIB_PATH = '/tmp/ORLIB/ORLIB-uncap/'
COST_VALUES_PER_LINE = 7

# GA Parameters
POPULATION_SIZE = 150
ELITE_SIZE = 2 * POPULATION_SIZE // 3
MAX_GENERATIONS = 4000
MUTATION_RATE = 0.05
CROSSOVER_RATE = 0.3